### ISSUE TITLE
grid control is offset

### ISSUE THREAD

**Issue by gabrielflorit** [mapbox/mapbox.js#424]
I'm seeing the grid offset by 25px - in other words, I have to hover 25px down from the actual point, to get the popup. I've confirmed that this is due to other 3rd party CSS. It doesn't happen on any of the examples you provide.

It seems as if the grid takes its position cues from more than just the leaflet map element. Could this be the case? Where in the mapbox.js code should I look to get me started?

**Comment by gabrielflorit** [comment]
Perhaps a better question is: where's the code that determines where to lay out the grid?

**Comment by jfirebaugh** [comment]
What version of MapBox.js are you using? This sounds like a bug that was fixed in 1.0.4.

**Comment by gabrielflorit** [comment]
I'm using latest - built it from source.

**Comment by jfirebaugh** [comment]
You probably want to look at https://github.com/Leaflet/Leaflet/commit/84c5114345147c92a5ace28048088819bb7d4d96 and `L.DomUtil. getViewportOffset` in general. Several similar issues have cropped up there.

**Comment by gabrielflorit** [comment]
The offset is browser dependent: e.g. 10px in FF, about 25px in Chrome. Note that this is still happening with the latest release.

**Comment by jfirebaugh** [comment]
Is this still happening with v1.4.0?
